[build]
build-dir = "/tmp/rust-mos-build"
docs = false
host = ["x86_64-unknown-linux-gnu"]
extended = true
tools = ["cargo", "clippy", "rustfmt"]

[target.x86_64-unknown-linux-gnu]
llvm-config = "../llvm-mos/build/bin/llvm-config"
llvm-has-rust-patches = false

[llvm]
download-ci-llvm = false

[dist]
compression-formats = ["gz"]
